#!/bin/bash

source /usr/local/lib/entrypoint.sh

set -e -o pipefail

# Generate a working copy of the current gitolite-admin repository
log "Trusting current repository ..."
ssh-keyscan localhost >> ~/.ssh/known_hosts
log "Replicating current admin repository ..."
git clone git@localhost:gitolite-admin.git ~/gitolite-admin.git

rm --force "${0}"

