#!/usr/bin/make -f

image=gitolite
namespace=crashvb
tag=SNAPSHOT
name=$(image)-$(tag)

buildargs=--build-arg=org_opencontainers_image_created="$(shell date '+%Y%m%d%H%M')" \
	--build-arg=org_opencontainers_image_revision="$(shell git rev-parse --short=12 --verify HEAD)"

runargs=--env=GITWEB_GENERATE_PASSWORD=true \
	--publish-all
